[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "aoc24"
version = "0.0.1"
requires-python = ">=3.12"

[project.optional-dependencies]
dev = ["pre-commit==4.0.1", "pytest==8.3.4"]
